#!/bin/bash

set -e

[ -z "$PLUGIN_PATH" ] && exit 1
[ -z "$REDMINE_EXEC" ] && exit 1
[ -z "$REDMINE_PATH" ] && exit 1
[ -z "$REDMINE_VERSION" ] && exit 1

mkdir -p "${REDMINE_PATH}"
mkdir -p tmp log

case ${REDMINE_VERSION} in
master)
  REDMINE_SOURCE="http://svn.redmine.org/redmine/trunk"
  ;;

*)
  REDMINE_SOURCE="http://svn.redmine.org/redmine/tags/${REDMINE_VERSION}"
  ;;
esac

(
  set -x
  svn export --quiet --force "${REDMINE_SOURCE}" "${REDMINE_PATH}"
)

echo "Symlink plugin, assets and specs..."

mkdir -p "${REDMINE_PATH}/public/plugin_assets"

if [ ! -L "${REDMINE_PATH}/plugins/redmine_dashboard" ]; then
  ln -s "${PLUGIN_PATH}" "${REDMINE_PATH}/plugins/redmine_dashboard"
fi

if [ ! -L "${REDMINE_PATH}/spec" ]; then
  ln -s "${PLUGIN_PATH}/spec" "${REDMINE_PATH}/spec"
fi

if [ ! -L "${REDMINE_PATH}/db/seeds.rb" ]; then
  ln -s "${PLUGIN_PATH}/db/seeds.rb" "${REDMINE_PATH}/db/seeds.rb"
fi

if [ ! -L "${REDMINE_PATH}/test/fixtures/rdb" ]; then
  ln -s "${PLUGIN_PATH}/spec/fixtures" "${REDMINE_PATH}/test/fixtures/rdb"
fi

if [ ! -L "${REDMINE_PATH}/public/plugin_assets/redmine_dashboard_linked" ]; then
  ln -s "${PLUGIN_PATH}/assets" "${REDMINE_PATH}/public/plugin_assets/redmine_dashboard_linked"
fi

echo "Generate database configuration..."

${REDMINE_EXEC} genconf >"${REDMINE_PATH}/config/database.yml"

pushd "${REDMINE_PATH}"

(
  set -x
  bundle config set --local without 'rmagick'
)
(
  set -x
  bundle install --jobs=3 --retry=3
)
(
  set -x
  bundle exec rake generate_secret_token db:create:all db:migrate redmine:plugins:migrate db:test:prepare
)

popd
